// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: grpc_sample/v1/sample.proto

package grpc_samplev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_grpc_sample_v1_sample_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_sample_v1_sample_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_grpc_sample_v1_sample_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_grpc_sample_v1_sample_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_sample_v1_sample_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_grpc_sample_v1_sample_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserInfoResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_grpc_sample_v1_sample_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_sample_v1_sample_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_grpc_sample_v1_sample_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_grpc_sample_v1_sample_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_sample_v1_sample_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_grpc_sample_v1_sample_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_grpc_sample_v1_sample_proto protoreflect.FileDescriptor

const file_grpc_sample_v1_sample_proto_rawDesc = "" +
	"\n" +
	"\x1bgrpc_sample/v1/sample.proto\x12\x0egrpc_sample.v1\"$\n" +
	"\x12GetUserInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x13GetUserInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\")\n" +
	"\x11CreateUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"$\n" +
	"\x12CreateUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xbc\x01\n" +
	"\rSampleService\x12V\n" +
	"\vGetUserInfo\x12\".grpc_sample.v1.GetUserInfoRequest\x1a#.grpc_sample.v1.GetUserInfoResponse\x12S\n" +
	"\n" +
	"CreateUser\x12!.grpc_sample.v1.CreateUserRequest\x1a\".grpc_sample.v1.CreateUserResponseB\xb5\x01\n" +
	"\x12com.grpc_sample.v1B\vSampleProtoP\x01Z=github.com/takahiroaoki/protobuf/grpc_sample/v1;grpc_samplev1\xa2\x02\x03GXX\xaa\x02\rGrpcSample.V1\xca\x02\rGrpcSample\\V1\xe2\x02\x19GrpcSample\\V1\\GPBMetadata\xea\x02\x0eGrpcSample::V1b\x06proto3"

var (
	file_grpc_sample_v1_sample_proto_rawDescOnce sync.Once
	file_grpc_sample_v1_sample_proto_rawDescData []byte
)

func file_grpc_sample_v1_sample_proto_rawDescGZIP() []byte {
	file_grpc_sample_v1_sample_proto_rawDescOnce.Do(func() {
		file_grpc_sample_v1_sample_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_sample_v1_sample_proto_rawDesc), len(file_grpc_sample_v1_sample_proto_rawDesc)))
	})
	return file_grpc_sample_v1_sample_proto_rawDescData
}

var file_grpc_sample_v1_sample_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_sample_v1_sample_proto_goTypes = []any{
	(*GetUserInfoRequest)(nil),  // 0: grpc_sample.v1.GetUserInfoRequest
	(*GetUserInfoResponse)(nil), // 1: grpc_sample.v1.GetUserInfoResponse
	(*CreateUserRequest)(nil),   // 2: grpc_sample.v1.CreateUserRequest
	(*CreateUserResponse)(nil),  // 3: grpc_sample.v1.CreateUserResponse
}
var file_grpc_sample_v1_sample_proto_depIdxs = []int32{
	0, // 0: grpc_sample.v1.SampleService.GetUserInfo:input_type -> grpc_sample.v1.GetUserInfoRequest
	2, // 1: grpc_sample.v1.SampleService.CreateUser:input_type -> grpc_sample.v1.CreateUserRequest
	1, // 2: grpc_sample.v1.SampleService.GetUserInfo:output_type -> grpc_sample.v1.GetUserInfoResponse
	3, // 3: grpc_sample.v1.SampleService.CreateUser:output_type -> grpc_sample.v1.CreateUserResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_sample_v1_sample_proto_init() }
func file_grpc_sample_v1_sample_proto_init() {
	if File_grpc_sample_v1_sample_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_sample_v1_sample_proto_rawDesc), len(file_grpc_sample_v1_sample_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_sample_v1_sample_proto_goTypes,
		DependencyIndexes: file_grpc_sample_v1_sample_proto_depIdxs,
		MessageInfos:      file_grpc_sample_v1_sample_proto_msgTypes,
	}.Build()
	File_grpc_sample_v1_sample_proto = out.File
	file_grpc_sample_v1_sample_proto_goTypes = nil
	file_grpc_sample_v1_sample_proto_depIdxs = nil
}
